### ISSUE TITLE
Browser history when navigating around a PR

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#10]
Make the tabs on the pull request page push into your browser history stack. For example, going to a pull request, clicking say the Commits tab, then clicking the back button takes you back to the pull request list instead of back to the Conversation tab.

**Comment by benbalter** [comment]
@caabernathy Do you believe this is still the case? I just tested and believe what you describe is the current behavior.

**Comment by jeffmcaffer** [comment]
Seems like it works as desired now
