### ISSUE TITLE
Ability to triage issues without giving repo push access

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#14]
GitHub only allows issue triage by people with push access to repositories; several projects have an active community commenting with "This is a dupe of #1234", but they're not able to add the duplicate tag, or close the issue.

Would love to see the creation of more granular permissions on GitHub so repos could create teams with "triage" access to help with this.

**Comment by edunham** [comment]
This is huge for @rust-lang and @servo. We have a funnel of enthusiastic new contributors who want to help out, and we'd love to tell them "please follow this guide to triage issues"... But we can't give them permission to label issues without also giving them push access to the repository.

**Comment by benbalter** [comment]
While not ideal or a permanent solution, you can currently [use protected branches](https://ben.balter.com/2017/04/14/create-an-open-source-moderator-role-with-protected-branches-on-github/) to empower this role in most workflows.

**Comment by jeffmcaffer** [comment]
Is this addressed with the new Traige role?

**Comment by caniszczyk** [comment]
yep! thanks @jeffmcaffer https://github.blog/2019-05-23-build-like-an-open-source-community-with-github-enterprise/

**Comment by benbalter** [comment]
Additional details on the new roles in https://github.blog/changelog/2019-05-23-triage-and-maintain-roles-beta/.
