### ISSUE TITLE
Issue reminders

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#16]
For issues, it would be useful to get a notification if an issue hasn't been updated for a configurable period of time. The notification could go to the person assigned to the issue plus repo admins.

This would help for PR as well if we're able to assign PRs to authors. So if an update has been requested and the author hasn't made any changes, they can be pinged. Similarly if a review of the PR is in progress but it has stalled, the reviewer can be pinged.

**Comment by caniszczyk** [comment]
This is essentially possible via tools these days: https://probot.github.io/apps/reminders/

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-team
