### ISSUE TITLE
Separate place for discussions

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#18]
Some issues filed are not bugs but feature requests or discussions that may be long running. If these stay on the issues list this may look bad especially for active projects as people come in and wonder why there are so many open issues. Being able to have this in a separate discussions tab could alleviate this. This means project maintainers don't have to close the issue and move it off GitHub as they currently tend to do for some of our projects.

**Comment by clarkbw** [comment]
There is a separate place for team discussions https://help.github.com/articles/about-team-discussions/  It requires those people to be a part of the team so it doesn't solve for this entire use case.

**Comment by caniszczyk** [comment]
this is a new github feature, i.e., https://github.com/vercel/next.js/discussions
