### ISSUE TITLE
Prefill issue description

### ISSUE THREAD

**Issue by nzakas** [todogroup/gh-issues#2]
One of the pain points of managing issues on GitHub is that I find myself repeating the same questions over and over when new issues are filed:

1. What version are you using?
1. What did you do?
1. What was the actual output?

It would save a lot of time if we could prefill the description box on GitHub issues with a template (kind of like what we can do with the query string parameters....except permanent).

**Comment by willnorris** [comment]
resolved: https://github.com/blog/2111-issue-and-pull-request-templates
