### ISSUE TITLE
Default README template

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#22]
When creating a repo, having a default README for the org would be a nice way to drive a higher bar on quality of project's in their early days.

**Comment by RichardLitt** [comment]
Agreed. 

On the solution side, I've been doing two things to help with this: one, set up an example, blank repo with documents. And I also created [standard-readme](https://github.com/RichardLitt/standard-readme) to help with this.

**Comment by hwine** [comment]
Agreed on "org defaults" for a number of things (e.g. license, community guidelines, ...)

At the moment, another approach is to use [cookiecutter](https://github.com/audreyr/cookiecutter) to set up many good defaults for a new project. (Works for any language.)

**Comment by caniszczyk** [comment]
The project templates feature for GitHub takes care of this but it's up to you to provide the template: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository
