### ISSUE TITLE
Ability to backup entire repos with source, issues, ...

### ISSUE THREAD

**Issue by jeffmcaffer** [todogroup/gh-issues#25]
we can already clone the repos but need to get all the rest of the data (issues, pull requests, teams, ...)

**Comment by clarkbw** [comment]
This new API allows you to extract an entire archive of your repository.  https://blog.github.com/changelog/2018-05-24-personal-data-access/

**Comment by caniszczyk** [comment]
Thanks @clarkbw that's awesome!
