### ISSUE TITLE
Two-tier organization structure

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#30]
A structure of Overall-Corp / Org / Repo would be wonderful. Come up a lot in the room, but not sure it's in an issue yet.

========== Scenarios (added after the fact)

* Permissions management
* Teams sharing across orgs

**Comment by jeffmcaffer** [comment]
The new Enterprise Account feature is a start at this. Mostly focused at billing and accounting things right now but will hopefully evolve to include permissions management and "policy-like" notions. Would be awesome to flesh this out with ideas of what folks would want from this new top level

**Comment by kpfleming** [comment]
I brought this up in a lunch with chat in San Diego with Jeff as well; big +1 from me.

**Comment by jeffmcaffer** [comment]
Would be interesting to iterate on this to tease out the scenarios and prioritize and see the best way to address. I'll start adding scenarios on the original comment. Please edit and add yours...

**Comment by hyandell** [comment]
Closing this as I feel the Enterprise direction is getting there.
