### ISSUE TITLE
PullApprove Style Review Checks

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/gh-issues#34]
I would love to have something like PullApprove built into GitHub:
http://docs.pullapprove.com/yaml/

A lot of times, you want certain people to +1 pull requests before merging.

**Comment by fredemmott** [comment]
I've not used pullapprove - how similar is this to the new review features + required reviews on protected branches?

**Comment by caniszczyk** [comment]
@fredemmott it augments the new review features, I blogged a bit about this awhile ago here: https://aniszczyk.org/2016/08/04/improved-github-code-review-tools/

**Comment by jwsloan** [comment]
It looks like GitHub's [CODEOWNERS](https://github.com/blog/2392-introducing-code-owners) file may now get you what you're looking for.

**Comment by caniszczyk** [comment]
@jwsloan it definitely helps but doesn't have all the features needed (enforcing say at least 2 people need to look at it from the list of OWNERS).

**Comment by clarkbw** [comment]
You can require more than 1 reviewer now here ( https://blog.github.com/2018-03-23-require-multiple-reviewers/ )
