### ISSUE TITLE
Service accounts

### ISSUE THREAD

**Issue by nzakas** [todogroup/gh-issues#4]
One of the issues I'm frequently faced with is how to effectively create bots for our organization. At the moment, I've had to create a completely separate account for the bot, which means managing an additional username/password combination that needs access to everything but can't use 2FA to authenticate. Further, if the bot gets sufficiently busy, it will run up against the 5000 request API limit, necessitating another account.

I'd really like to have the equivalent of service accounts (like how Google did it) that could be used for bots. These could be tied directly to the organization so they could be managed easily.

**Comment by edunham** [comment]
+1. This is especially relevant to the Rust and Servo projects, as we use a variety of bots to implement features that GitHub does not yet offer (such as auto-merging an r+'d PR once the tests pass).

**Comment by bkeepers** [comment]
[Integrations](https://developer.github.com/early-access/integrations/) Early Access was shipped last week, which aims to do exactly this. Please check it out, and share any feedback on the [Platform Forum](https://platform.github.community).
