### ISSUE TITLE
Web-based operations should use the organization email address

### ISSUE THREAD

**Issue by jparise** [todogroup/gh-issues#40]
It appears that all web-based git operations (edits, merges, etc.) use the account's primary email address. It would be a lot nicer if those operations used the email address that's configured via [the organization-specific notifications routing matrix](https://help.github.com/articles/managing-notification-emails-for-organizations/) instead.

**Comment by willnorris** [comment]
See also #32

**Comment by jparise** [comment]
Closing in favor of #32.

**Comment by anirudh-hegde** [comment]
Should I set my college Email-id as primary email address on my GitHub account?
