### ISSUE TITLE
Require 2fac for repo collaborators

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#41]
For organization members API, ?filter=2fa_disabled allows us to audit access. This doesn’t appear to work for collaborators added to just a repo instead (at least via the invitations/collaborators APIs).

**Comment by jeffmcaffer** [comment]
would add more thumbs up if I could...

**Comment by bkeepers** [comment]
Similar to #7, which is now :shipit:. You can enforce all members and collaborators have 2FA enabled.
