### ISSUE TITLE
Optionally disable the merge/squash buttons on pull requests

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#42]
Disable the 'merge'/'squash' buttons on pull requests for repos that merge via some other method.

Some of our projects don't want merges via the GitHub UI. The merge flow via the GitHub UI frequently leads to one forgetful person using it and then hours of follow-on work to get the code back in sync.

**Comment by caniszczyk** [comment]
<img width="647" alt="Screen Shot 2020-06-05 at 12 29 05 PM" src="https://user-images.githubusercontent.com/63777/83906042-69931a00-a728-11ea-91d8-be0407840df3.png">

This is possible now.

**Comment by CH-RhyMoore** [comment]
The above says "at least one option must be enabled." The OP says "disable" which means to me "no options have to be enabled."

Sure, you can disable merging and squashing and leave only rebasing. But that still leaves rebasing. Which has the extra constraint per documentation of always changes SHAs, even when not strictly necessary...a fairly major constraint.
