### ISSUE TITLE
Give third-party apps access to a single repo

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#43]
Make it possible to give apps access to **one** private repo and not not every one in the org.

**Comment by jaredsmith** [comment]
If I understood correctly from the launch of "integrations" at GitHub Universe yesterday, 3rd party apps using the "integrations" functionality can now be given access to individual repos.

**Comment by hyandell** [comment]
Christine - did integrations solve your wish here?

**Comment by bkeepers** [comment]
GitHub Apps (formerly "integrations") are now the preferred way for integrating with GitHub, and they have this feature. I'm going to call this done, but feel free to reopen if I'm not understanding the original request.
