### ISSUE TITLE
Sane LFS billing strategy

### ISSUE THREAD

**Issue by jeffmcaffer** [todogroup/gh-issues#45]
The current LFS Billing model is monthly use it or lose it.  This makes it very hard to structure significant usage without a very clear understanding of consumption.  With no control of, for example, clones or coding/design patterns projects can easily and quickly overrun their limits.  Need to have a more manageable model.

**Comment by caniszczyk** [comment]
@jeffmcaffer says to close this one

https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-git-large-file-storage
