### ISSUE TITLE
Multiline comments for code reviews

### ISSUE THREAD

**Issue by jparise** [todogroup/gh-issues#47]
One of the features I miss most when moving between Phabricator and GitHub is the ability to associate a comment with a range of lines from a diff.

GitLab is tracking a similar feature request: https://gitlab.com/gitlab-org/gitlab-ce/issues/4143

**Comment by caniszczyk** [comment]
This is possible now: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request
