### ISSUE TITLE
Enforce DCO per repo or org

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/gh-issues#48]
it would be great to have DCO enforced on a repo
https://developercertificate.org/

An external tool like PullApprove handles this already:
https://docs.pullapprove.com/requirements/signed_off_by/

**Comment by bkeepers** [comment]
Here's a work in progress GitHub Integration that adds DCO checks on commits and pull requests: https://github.com/probot/dco/pull/2

It's only a few hours old, so it's not ready for production use yet, but feel free to follow along for updates there. Feature requests welcome.

FYI @mkdolan

**Comment by bkeepers** [comment]
I think the integration linked to above solves this and will likely be the preferred way to enforce the DCO going forward.
