### ISSUE TITLE
GitHub API rate limiting:: Dev/Prod

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#5]
One pain I have is that I don't have separate development and production GitHub API rate limiting. So I have to be careful not to play around with development code during the hours my production dashboard pulls data.

**Comment by willnorris** [comment]
For comparison, we have separate accounts and orgs on GitHub that our internal development environments use:

Prod: https://github.com/google managed by https://github.com/google-admin
Dev: https://github.com/google-test managed by https://github.com/google-admin-test

We do this less for API quota, but more to ensure I don't do something stupid with our production org.

**Comment by jeffmcaffer** [comment]
@hyandell, closable?

**Comment by jeffmcaffer** [comment]
Seems like there's a reasonable workaround
