### ISSUE TITLE
Reporting CVEs to projects

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#52]
I'd like a process to report security issues to projects, and to have security issues reported to my organization, without having to do it in public. I suspect this comes down to private issues (i.e. only the requester and anyone with Write permission can read the issue). 

Ideally the same would hold for pull requests; which would help with projects who don't have issues turned on.

**Comment by caniszczyk** [comment]
It would be nice to have something built into GitHub or just the ability to make private issues.

We are currently evaluating some external services like hackerone for CVE coordination.

**Comment by caniszczyk** [comment]
this has come up again today, would be nice :)

**Comment by Dor1s** [comment]
+1, private issues would be super helpful

**Comment by jeffmcaffer** [comment]
Does the new Maintainer Security Advisories address this?

**Comment by caniszczyk** [comment]
yep

**Comment by caniszczyk** [comment]
wfm
