### ISSUE TITLE
"Support" team permissions group

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#54]
It would be very useful to define a new type of permission level called Support.

It's someone who can close an issue and pull request, but can't touch the code; so no Pull Request merging.

**Comment by hwine** [comment]
I agree on closing/managing issues, and ambivalent on PR close

**Use case:** some larger open source projects have volunteers who just handle issue triage. Right now, they must be given commit access to deal with the issues.

**Comment by benbalter** [comment]
I believe this may be similar to https://github.com/todogroup/gh-issues/issues/14. There, I recommended:

> While not ideal or a permanent solution, you can currently [use protected branches](https://ben.balter.com/2017/04/14/create-an-open-source-moderator-role-with-protected-branches-on-github/) to empower this role in most workflows.

**Comment by jeffmcaffer** [comment]
Does the new Triage role fit the bill here?

**Comment by hyandell** [comment]
I think so.
