### ISSUE TITLE
Separate third party permissions at the repository level

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#6]
It's quite scary to give third parties the broad access they ask for, to every repository in an organization. I'd really like to be able to do this at the repository level. 

This is with the third-party application access turned on.

**Comment by clarkbw** [comment]
☝️ This is mostly solved by GitHub Apps ( https://developer.github.com/v3/apps/permissions/ )

**Comment by jeffmcaffer** [comment]
Feels like this one can be closed in as much as the oauth app perms model is unlikely to change here and GitHub apps provide the capability. Sucks when being asked to add an oauth app to an org but the push back to the oauth app author should be "get on GitHub apps"

@hyandell you agree with closing?

**Comment by hyandell** [comment]
Sure.
