### ISSUE TITLE
Enforcing 2FA for an organization

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#7]
Restrict members from joining an organization unless they have 2 factor authentication turned on, and disable access if they later remove 2FAC. If possible, this would be a UI setting on github.com.

**Comment by edunham** [comment]
Preventing the addition of password-only accounts to an org would be huge -- as far as I know, there's currently no way to tell whether or not a user has 2FA until they have accepted your org's invitation to join. 

It would also be great for GitHub to automate the process of warning users without 2FA that they will soon lose access, then disabling all accounts without 2FA on a specific date.

**Comment by hwine** [comment]
> It would also be great for GitHub to automate the process of warning users without 2FA that they will soon lose access, then disabling all accounts without 2FA on a specific date. 

Agreed, and in the meantime an owner can run a script similar to https://github.com/mozilla/github-org-scripts/blob/master/enforce_2fa.py. (Could be refactored for easier usage elsewhere. PRs welcome :)

**Comment by bkeepers** [comment]
This shipped at GitHub Universe last week: https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/
