### ISSUE TITLE
Default Notification Email Address not working?

### ISSUE THREAD

**Issue by MattyAyOh** [todogroup/gh-issues#71]
I have always had a personal GH account

A couple years ago we made a GH Organization, and I set GH emails to send to my new work email

So now all PRs/Issue notification emails go to my work email instead of my personal

Recently I wanted to change this to set my default notification email to go to another address, but it doesn't appear to be working? Emails are still going to my work email.  

Is this because of the organization level? We have members in our organization who don't have emails with our work domain. 

I tried looking at all of the settings and cannot find anything. I'm going to be losing my work email so I wanted to sort this out

**Comment by justaugustus** [comment]
You can customize notifications per GitHub organization. See here: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#choosing-where-your-organizations-email-notifications-are-sent
