### ISSUE TITLE
Useful for repositories to display the date when they were archived

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/gh-issues#74]

**Comment by ashleywolf** [comment]
Sharing from the TODO Group Slack channel. From @lumaxis: I work on the OSPO engineering team at GitHub and we're looking into adding this date to the GitHub UI. Unfortunately, it may be that we can only show this for newly archived repos going forward. Would this still be valuable?

**Comment by jzb** [comment]
@ashleywolf It would still be valuable. Maybe for older archived repos just a note that says something like "archived before October 7, 2022" with a note? Either way, still valuable.

**Comment by lumaxis** [comment]
The change to show repo archival dates just went live! 🙌🏼 

https://github.blog/changelog/2022-11-23-repository-archive-date-now-shown-in-ui/

**Comment by ahpook** [comment]
I mistakenly closed #77 instead of this one.
