### ISSUE TITLE
Archive Message & Notifications

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#78]
When Archiving a repository, it would be very valuable to be able to tell the users something. Currently folk tend to squeeze it into the README, but that makes the project look more active than it is, and tends to make the individual doing the cleanup the target for followup.

Ideally you would go to archive a repository, the popup would include a textarea of N hundred characters in which you put a short message on the archiving of the repository. This can either include a link, or there is a "See Instead" field that can take a link.

In addition to displaying this on the repository when archived, this message could also be used to notify Watchers of the repository about the archiving, and possibly reporters of open issues/pull requests (if not automatically made Watchers).

This archive message would remain editable even when the repository itself is archived.

**Comment by ahpook** [comment]
We opted not to do this when picking up the org and repo archiving work recently. It's a good idea, but there's an easy workaround (editing the README), and having to extend the database to include arbitrary archive text is way more work than it's worth. Sorry.
