### ISSUE TITLE
Org-wide script assistance

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#79]
A lot of Enterprise or Org management involves wanting to run scripts across a set of repositories. 

I think there's more that GitHub could do here to make that easier. Which could be ranging from the GitHub OSPO/TODOGroup managing a repository of common scripts/script framework for OSPOs, to education on doing this with hosted solutions (Apps/Actions *wave hands*), to campaigning for something new in GitHub Hosted land that lets the Org Owners have an execution environment for said 'scripts'.

Things like.... "Hmmm...how many of our Teams have no members?"   "How many of our repos have no one with permissions on them?" etc.

**Comment by ahpook** [comment]
We have started to do this in the github-ospo repo: https://github.com/github/github-ospo/blob/main/README.md#actions 
If you've got additional actions you'd like to include in the list (or ones you'd like us to write!) please raise PRs or issues in the github-ospo repo!
