### ISSUE TITLE
Notifications on a PR update

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#8]
GitHub doesn't send notifications on a PR when a new commit is added or a force push happens. This makes it difficult to tell when a PR has been updated and needs to be looked at.

What we've done as a workaround is have an external bot that checks for a PR code change, then leaves a comment to trigger the notification. This is not ideal but it works.

**Comment by benbalter** [comment]
I recognize that this is an older issue, but believe that this is the current behavior. See https://help.github.com/articles/choosing-the-types-of-notifications-you-receive/#enabling-email-service-notifications-for-pushes-to-your-repository.

**Comment by jeffmcaffer** [comment]
Think we're good here.
