### ISSUE TITLE
Org Member Training

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#80]
OSPOs are supporting a large number of folk using GitHub. Training often becomes a topic. I'm not sure how much GitHub can help here, but I'm interested in what could be done. Can org owners have a banner to say "Take Your X Training!!! <internal link>" that is turned off when the org owner marks them inside GitHub as 'now trained on <X>".

**Comment by ahpook** [comment]
This may be fixed now - it's not for training specifically but there are organization wide announcements available that show up in this kind of banner. They can be marked as dismissable by the user or not. 

I can't imagine implementing the full expression of this, where there would be some kind of arbitrary API call that we'd use to determine whether to display the banner or not...?



![Image](https://github.com/todogroup/gh-issues/assets/56753/9cc2402d-edb4-4631-8b25-17f2f6ca8d2b)

**Comment by ahpook** [comment]
Going to close this as it's now possible, please re-open if I've misunderstood.
