### ISSUE TITLE
Filename search in search UI

### ISSUE THREAD

**Issue by hyandell** [todogroup/gh-issues#83]
Mentioning because I don't think I've ever flagged it before.

It's very frustrating to search in the top search bar for a filename, only to realize that's not one of the options available and you have to go to Goto File in the Explorer UI. Would love the main search to search on filenames too.

**Comment by ahpook** [comment]
I believe this is fixed with the new code search interface : https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#path-qualifier

**Comment by ahpook** [comment]
Closing as fixed, please reopen if I've misunderstood the issue.
