### ISSUE TITLE
Make it easier to process PR notification emails

### ISSUE THREAD

**Issue by caabernathy** [todogroup/gh-issues#9]
It would be really useful to have subject headers in the notification emails to tell you if it relates to

a) a PR you authored
b) a PR you are being tagged in
c) a PR on a repo you just happen to watch,
d) PR assigned to you
For bonus points (e) a PR you've commented on previously would be awesome. 

Currently all the emails are the same so that on busy repos it's easy to completely miss things you are tagged in because it's just one of a million emails from GitHub.

**Comment by benbalter** [comment]
@caabernathy while not in the subject, it is possible to filter the notification type by the `cc` field. See https://help.github.com/articles/about-email-notifications/.

**Comment by jeffmcaffer** [comment]
There has been a massive evolution in the area of notifications. Closing. Please reopen if there are cases not covered.
